on:
  pull_request

name: Envs
jobs:
  print-envs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: pull_request | Get the target branch
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        cat LICENSE

    - name: Log into ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
