on:
  pull_request

name: Envs
jobs:
  print-envs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Rebase
      run: |
        git config user.email "user@email.com"
        git config user.name "User Name"
        git remote add upstream https://github.com/fidencio-gha-tests/test-stuff
        git remote update upstream
        git rebase upstream/main

    - name: pull_request | Get the target branch
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        cat LICENSE
